import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LoginForm from './components/LoginForm'
import Login from './Login'

export default function Home() {
  console.log("jiii"
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Title hasdfsdf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Login />
        <LoginForm />
      Hiii
      </main>

    </div>
  )
}
